CREATE TYPE user_role AS ENUM ('ROLE_USER', 'ROLE_ADMIN');
CREATE TYPE email_token_type AS ENUM ('EMAIL_CONFIRMATION', 'PASSWORD_RESET');
CREATE TYPE book_source AS ENUM ('GOOGLE_BOOKS', 'MANUAL');
CREATE TYPE reading_status AS ENUM ('TO_READ', 'READING', 'READ', 'ABANDONED');